name: Build And Publish Go-KAS Docker image

on:
  push:
    branches:
      - PLAT-2416-kas-replace-python-go
  pull_request:
    branches:
      - PLAT-2416-kas-replace-python-go
  release:
    types: [published]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Extract version
        run: |
          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
        id: info
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and test
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: false
          target: tester
  build-and-push:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Extract version
        run: |
          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
        id: info
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          target: server-debug
          push: true
          tags: ghcr.io/opentdf/gokas:${{ env.VERSION }}
